version: '3'

services:
  web:
    image: phone-aggregator:1.0.0
    container_name: "phone-aggregator-service"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"